SASS-7878: Audit events for property income expenses
hmrc/income-tax-property-frontend pull request #146
Opened 2024-04-22 14:18 UTC by vivekhmrc

2024-04-23 15:27 UTC, arunkumar461 requested changes
just enable debug logs and share the JSON within the group

2024-04-23 15:27 UTC, arunkumar461 commented on app/audit/PropertyRentalsExpense.scala
> +case class PropertyRentalsExpense(consolidatedExpensesYesNo: Option[Boolean],
consolidatedExpenses is an object; you may need to include the amount as well

2024-04-23 15:27 UTC, arunkumar461 commented on app/audit/PropertyRentalsIncome.scala
> +case class PropertyRentalsIncome(calculatedFigureYourself: Option[Boolean],
calculatedFigureYourself is an object, same here

2024-04-24 10:28 UTC, modivilioglu approved these changes
LGTM

2024-04-24 10:30 UTC, merged