SASS-8125 - FE-BE Integration - Property Rentals Adjustments CYA
hmrc/income-tax-property-frontend pull request #198
Opened 2024-06-02 20:43 UTC by modivilioglu

2024-06-04 17:34 UTC, arunkumar461 requested changes

2024-06-04 17:34 UTC, arunkumar461 commented on app/connectors/PropertySubmissionConnector.scala
> +                  ctx: JourneyContext,
reuse saveJourney method?

2024-06-05 14:24 UTC, vivekhmrc approved these changes

2024-06-05 14:30 UTC, modivilioglu commented on app/connectors/PropertySubmissionConnector.scala
> +                  ctx: JourneyContext,
Incorporated.

2024-06-05 14:31 UTC, vivekhmrc commented on app/connectors/PropertySubmissionConnector.scala
> +                  ctx: JourneyContext,
Thanks @arunkumar461 / @modivilioglu

2024-06-05 14:32 UTC, merged