Rentals & RaR - Allowances section: Create 'Have you finished this se…
hmrc/income-tax-property-frontend pull request #335
Opened 2024-08-22 14:13 UTC by willjshark

…ction?' page

2024-08-22 16:05 UTC, arunkumar461 requested changes

2024-08-22 16:05 UTC, arunkumar461 commented on app/controllers/rentalsandrentaroom/allowances/RentalsRaRAllowancesCompleteController.scala
> +class RentalsRaRAllowancesCompleteController @Inject()(
Could you make this controller more generic? I hope you recall the discussion we had during the refactoring session. Discuss with Costas or we can have a tech huddle tomorrow

2024-08-22 16:06 UTC, arunkumar461 commented on app/controllers/rentalsandrentaroom/allowances/RentalsRaRAllowancesCompleteController.scala
> +class RentalsRaRAllowancesCompleteController @Inject()(
@cmantzoukashmrc

2024-08-27 15:27 UTC, arunkumar461 approved these changes

2024-08-27 15:30 UTC, vivekhmrc approved these changes

2024-08-27 16:31 UTC, merged