Sass 9178
hmrc/income-tax-property-frontend pull request #364
Opened 2024-09-16 08:29 UTC by modivilioglu

2024-09-16 11:01 UTC, arunkumar461 requested changes

2024-09-17 13:10 UTC, modivilioglu commented on app/controllers/enhancedstructuresbuildingallowance/EsbaCheckYourAnswersController.scala
>    private def auditCYA(
done.

2024-09-17 13:10 UTC, modivilioglu commented on app/controllers/enhancedstructuresbuildingallowance/EsbaClaimsController.scala
> +    val context = JourneyContext(taxYear, request.user.mtditid, request.user.nino, "rentals-and-rent-a-room-esba")
done.

2024-09-17 13:57 UTC, modivilioglu commented on app/controllers/enhancedstructuresbuildingallowance/EsbaClaimsController.scala
> +            request.userAnswers.get(EsbasWithSupportingQuestionsPage(propertyType)) match {
done.

2024-09-18 08:17 UTC, arunkumar461 approved these changes

2024-09-18 09:26 UTC, merged