SASS-9686: Foreign Property - Expenses section: 'Consolidated or individual expenses' page
hmrc/income-tax-property-frontend pull request #457
Opened 2024-11-27 13:46 UTC by StuartJamesProctor

2024-11-28 14:03 UTC, tapiwa-tiyemba approved these changes

2024-11-28 14:25 UTC, tapiwa-tiyemba requested changes
conflicts to resolve

2024-11-29 09:44 UTC, tapiwa-tiyemba approved these changes

2024-12-03 12:13 UTC, vivekhmrc approved these changes

2024-12-03 12:49 UTC, tapiwa-tiyemba submitted a review, later dismissed

2024-12-03 16:02 UTC, zmdnoor approved these changes

2024-12-03 16:09 UTC, merged