SASS-9711:Allowances section: Create 'Allowances' Hyperlink and Allow…
hmrc/income-tax-property-frontend pull request #461
Opened 2024-12-02 13:19 UTC by RGlossop

…ances Intro Pages

2024-12-02 15:48 UTC, vivekhmrc submitted a review, later dismissed

2024-12-03 16:26 UTC, tapiwa-tiyemba commented on app/controllers/foreign/allowances/ForeignPropertyAllowancesStartController.scala
> +        }).get.name
Hey @RGlossop you shouldn't use .get on an option. Please update this.

2024-12-04 11:00 UTC, tapiwa-tiyemba commented on app/controllers/foreign/allowances/ForeignPropertyAllowancesStartController.scala
> +            Ok(view(taxYear, countryCode, countryName, request.user.isAgentMessageKey, propertyData.accrualsOrCash.get))
We need to properly handle the case where accrualsOrCash is None

2024-12-04 16:28 UTC, tapiwa-tiyemba commented on app/controllers/foreign/expenses/ForeignPropertyExpensesStartController.scala
> +
you need a case for when income is None

2024-12-05 09:14 UTC, tapiwa-tiyemba requested changes

2024-12-05 09:14 UTC, tapiwa-tiyemba commented on app/controllers/foreign/allowances/ForeignPropertyAllowancesStartController.scala
> +          propertyData.accrualsOrCash.getOrElse(None) match {
same here

2024-12-05 14:45 UTC, tapiwa-tiyemba approved these changes

2024-12-05 14:59 UTC, merged